name: Deploy 11ty to Server via SCP

on:
  push:
    branches:
      - main  # Run when you push to main (or another branch)

jobs:
  build-deploy:
    runs-on: ubuntu-latest  # Use an Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Adjust based on your Node version

      - name: Install dependencies
        run: npm install

      - name: Build the site with 11ty
        run: npm run prod

      - name: Copy folder content recursively to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: _site  # Local directory to be copied
          remote: /var/www/curious-grapes.one/  # Remote target directory
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.KEY }}
